name: TeamChat
version: '${version}'
main: org.example.jinhhyu.teamchat.TeamChat
api-version: '1.21'
commands:
  t:
    description: Team chat and team management
    usage: /t <invite|join|leave|chat|message>
